### ISSUE TITLE
Wrong Pinout

### ISSUE THREAD

**Issue by AtMostafa** [Karpova-Lab/pyControl-D-Series-Breakout#1]
Hello,

I managed to run the SPI2 port after days of struggle. The issue was the mistake in the pinout of Port2 DIO_B which based on the spreadsheet is the clock line, but it's not.
I noticed that DIO_B and C have been swapped on the website since I printed down my copy, but I think it is still wrong in the spreadsheet.

**Comment by alustig3** [comment]
The spreadsheet has been corrected in aca1b7563fcda5f1fbce0720579d3f11688c5208

Sorry the mistake caused you trouble. Thanks so much for reporting the issue!
