### ISSUE TITLE
SPI chip select

### ISSUE THREAD

**Issue by AtMostafa** [Karpova-Lab/pyControl-D-Series-Breakout#6]
In micropython version 1.18 (and possibly earlier versions), the Chip Select (or SS) line of the hardware SPI is configurable by the user, from [docs](https://docs.micropython.org/en/v1.9.3/wipy/library/machine.SPI.html):
> Management of an SS signal should happen in user code (via machine.Pin class)

So multiple devices can easily share only one SPI bus and have their own CS, [here](https://github.com/BeNeuroLab/PyTreadmillTask/blob/a54120618892bfddf0d39d9f1b2b57f999ccef32/devices/_PMW3360DM.py#L343) is an example of 2 mouse sensors sharing SPI2.

Pretty minor, but I think it's nicer to update the SPI table on the website ([here](https://github.com/Karpova-Lab/pyControl-D-Series-Breakout/blob/7e3bf519f14bf59fba8e6f6569546ace7d7827d5/mkdocs/src/using.md?plain=1#L54)) so people don't think they are restricted to the specified CS pin :)

Bests,

**Comment by alustig3** [comment]
Ah yes you're absolutely right. Thanks so much for pointing that out!

fixed in 999bcb788e3a692fdda5ce456eb1d312666dd67d
